### ISSUE TITLE
about simple-dashboard.html

### ISSUE THREAD

**Issue by vdfdfhgbstdh** [m-ahmadi/tse-client#1]
hey, 
simple-dashboard.html not working! can u tell me how can i use it(more explain)? i'm a noob :))

**Comment by m-ahmadi** [comment]
Hi, You must enable `CORS` in your browser for example with [Allow CORS](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf) in Chrome.

Also, you should place this file inside a web server public directory, and open `localhost/simple-dashboard.html` in browser.

If you have `Apache` on your machine move `simple-dashboard.html` to your `htdocs` folder.
If you have `node.js` on your machine do `npm i -g http-server` and then `http-server path/to/simple-dashboard.html`, and open `localhost:8080/simple-dashboard.html` in browser.

**About CORS**
Basically, the browser does not allow you to download data from `http://foo.com` when your current address is `http://bar.com`,
except in some cases, for example:
- A server that is configured to allow it
- A cross-origin URL that is inside `<img/>` or `<link rel=stylesheet />` or `<script>` or `<iframe>` or `<video>`

You can read more about `CORS` in [this page](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing):
> A web page may freely embed cross-origin images, stylesheets, scripts, iframes, and videos.

> Certain "cross-domain" requests, notably Ajax requests, are forbidden by default by the same-origin security policy.
