### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by 1mahdimf** [m-ahmadi/tse-client#2]
با سلام
بعد نصب و هنگام اجرا این خطا رو نشان میده
ممنون میشم راهنمایی کنید

`(node:44660) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'red' of undefined
    at D:\laragon\bin\nodejs\node-v14.17.5\node_modules\tse-client\index.js:128:61
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:44660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by m-ahmadi** [comment]
سلام

در چه ورژنی این اتفاق میوفته؟
`tse -v`

و همچنین در چه کامندی؟
مثلا در

`tse فولاد -b 5d -o .`
یا
`tse itd فولاد -b 5d -o .`

...می تونید این کار رو تست کنید و ببینید آیا همچنان همین خطا رخ میده

محتویات فولدر کش `tse --cache-dir` رو به صورت موقتی به یک جای دیگری کپی کنید 
مثلا با `robocopy tse-cache tmp /e` 

سپس محتویات فولدر کش رو کاملا پاک کنید (خود فولدر رو پاک نکنید و فقط محتویاتش رو پاک کنید)
مثلا با `del tse-cache\* /s/q`

حالا دوباره اون کامندی رو که خطا میداد رو اجرا کنید ببینید آیا همچنان اون خطا برقرار هست؟

**Comment by 1mahdimf** [comment]
با ایجاد پوشه
cache-dir
مشکل حل شد.ممنون

فقط چطور می تونم مسیر این پوشه کش رو عوض کنم؟

**Comment by m-ahmadi** [comment]
مسیر فولدر کش رو میشه با `tse --cache-dir  d:\abc` عوض کرد
