### ISSUE TITLE
CORS error 

### ISSUE THREAD

**Issue by AhmadPirzargar** [m-ahmadi/tse-client#3]
Hi,
When running each browser test I get a CORS error.
![Screenshot from 2021-08-14 15-13-57](https://user-images.githubusercontent.com/17249092/129443890-dbd0f660-41bc-444f-b992-2c0966735036.png)

Thank you for any help.

**Comment by m-ahmadi** [comment]
Hi,

You either have to install a [Chrome](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/access-control-allow-origin/) extension and enable `CORS` requests. (which is what I do most of the time)

or you have to set up a proxy server on your machine and set `tse.API_URL` to point to that server.
for example look at this [simple `php` proxy](https://github.com/m-ahmadi/tse-client#using-behind-a-simple-php-proxy)

**Comment by m-ahmadi** [comment]
One extra note:
You should serve these files through a web server,
and not opened like `file:///tse-client/test/browser/basic.htm`,
but rather like `http://localhost/tse-client/test/browser/basic.htm`.
