### ISSUE TITLE
تعدیل اشتباه یا درست ؟

### ISSUE THREAD

**Issue by thevilx** [m-ahmadi/tse-client#4]
سلام ، بنده برای پروژه ای از روش تعدیل قیمتی شما استفاده کردم ولی به مغایرت قیمتی با نمودار های آگاه و رهاورد خوردم و حتی در همین اپلیکشن نیز اعداد مغایرت دارند با این که تدیل به درستی انجام یافته است.
مثال : سهم فرابورس در تاریخ 2021-03-031
قیمت در tseclient : 1100
قیمت در کارگزاری ها : 1260
به نظرتون مشکل از کجاست ؟

**Comment by m-ahmadi** [comment]
سلام

روش تعدیلی که در این ماژول استفاده شده همانی هست که در خود نرم افزار رسمی بورس هست، من فقط اون کد  سی شارپ رو تبدیل به جاواسکریپت کردم

در صورتی که بین دیتای این ماژول و نرم افزار رسمی اختلاف باشه، اون یعنی یه جای کار ایراد داره

شما همین مورد مثالی که انجام دادید رو با نرم افزار رسمی هم مقایه کنید

**Comment by thevilx** [comment]
درسته ، برسی کردیم نرم افزار و این روش مشکلی نداشت ظاهرا مشکل از دیتابیس بعضی از این کارگزاری هاست که به غلط تعدیل انجام داده اند که برای بنده بسیار عجیب است ... موفق باشید ممنون از پاسختون

**Comment by m-ahmadi** [comment]
البته من به واسطه این ایشو به یک باگه دیگری در کد پی بردم که سعی میکنم در `2.14.13` رفعش کنم

**Comment by SamHanks94** [comment]
> من فقط اون کد سی شارپ رو تبدیل به جاواسکریپت کردم

سلام و تشکر از ریپوهای خوبی که اپن سورس کردین
میشه لطفا بفرمایید اون کد سی شارپ رو کجا میشه پیدا کرد؟

**Comment by m-ahmadi** [comment]
سلام و سپاس، در این آدرس است:
https://github.com/m-ahmadi/tsecorig
این کد ☝ توسط برنامه dotPeek تولید شده، (من فقط تغیراتی جزئی درش دادم)
